baseURL = "https://Aurora564.github.io/"       # 发布后改成真实地址
languageCode = "zh-cn"
title = "Aurora Blog"
theme = "PaperMod"                     # 主题名必须匹配目录

enableRobotsTXT = true

[pagination]
  pagerSize = 8

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"       # 支持“系列文章”

# ---- 主题参数 ----
[params]

  # 站点基本
  description = "技术、读书与思考"
  defaultTheme = "auto"          # dark/light/auto
  disableThemeToggle = false     # 是否禁用主题切换按钮

  ShowReadingTime = true         # 显示阅读时长
  ShowShareButtons = true        # 显示社交分享按钮
  ShowPostNavLinks = true        # 显示上一/下一篇链接

  # 首页 Info 信息
  [params.homeInfo]
    Title = "Aurora Blog"
    Content = "技术沉淀 · 阅读笔记 · 深度思考"
    AlignSocialIconsTo = "center"

# 菜单导航
[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "分类总览"
url = "/categories/"
weight = 2

[[menu.main]]
name = "系列总览"
url = "/series/"
weight = 3

[[menu.main]]
name = "关于"
url = "/about/"
weight = 4
